Repository Soju06/python-kis, pull requests merged in 2024-11, with the labels that each got.

#51 미체결 주문 객체 KisOrder 프로토콜 지원
  pykis/adapter/account_product/order_modify.py
  pykis/adapter/websocket/execution.py
  pykis/api/account/daily_order.py
  pykis/api/account/order.py
  pykis/api/account/order_modify.py
  pykis/api/account/pending_order.py
  pykis/api/websocket/order_execution.py
  pykis/client/websocket.py
  pykis/event/filters/order.py
  pykis/event/handler.py
Labels: 버그, 기능

#52 인증 토큰 만료 오류 핸들링
  pykis/kis.py
Labels: 버그

#53 해외주식 실시간 체결 이벤트 버그 수정
  pykis/api/account/order.py
  pykis/api/websocket/__init__.py
  pykis/api/websocket/order_execution.py
  pykis/event/filters/order.py
  pykis/responses/websocket.py
Labels: 버그

#54 누락된 타입 추가
  pykis/__init__.py
  pykis/types.py
Labels: 버그

#55 이벤트 티켓 암시적 구독 해지 경고 메시지 추가
  pykis/api/websocket/order_execution.py
  pykis/event/filters/product.py
  pykis/event/filters/subscription.py
  pykis/event/handler.py
Labels: 기능

#56 코드 리펙토링
  pykis/adapter/account/balance.py
  pykis/adapter/account/order.py
  pykis/adapter/account_product/order.py
  pykis/adapter/account_product/order_modify.py
  pykis/adapter/product/quote.py
  pykis/adapter/websocket/execution.py
  pykis/adapter/websocket/price.py
  pykis/api/account/balance.py
  pykis/api/account/daily_order.py
  pykis/api/account/order.py
  pykis/api/account/order_modify.py
  pykis/api/account/order_profit.py
  pykis/api/account/orderable_amount.py
  pykis/api/account/pending_order.py
  pykis/api/base/account.py
  pykis/api/base/market.py
  pykis/api/base/product.py
  pykis/api/stock/chart.py
  pykis/api/stock/info.py
  pykis/api/stock/order_book.py
  pykis/api/stock/quote.py
  pykis/api/stock/trading_hours.py
  pykis/api/websocket/order_execution.py
  pykis/api/websocket/price.py
  pykis/client/form.py
  pykis/client/object.py
  pykis/event/filters/order.py
  pykis/event/filters/product.py
  pykis/responses/dynamic.py
  pykis/responses/response.py
  pykis/responses/websocket.py
  pykis/scope/account.py
  pykis/scope/stock.py
  pykis/utils/params.py
  pykis/utils/repr.py
Labels: 기능

#57 fix: SyntaxError: f-string: expecting '}' but got "}"
  pykis/event/handler.py
Labels: 버그

#59 fixed #58: session 추가
  pykis/kis.py
Labels: 버그
